### ISSUE TITLE
Getting Error while building the Project using docker

### ISSUE THREAD

**Issue by RajikaJain** [tw-haiven/haiven-sample-knowledge-pack#1]
I am unable to build the Haiven project due to a missing `brainstorming` folder, which seems to have been deleted. The error log indicates that the application requires this folder for its functionality.
1. 
<img width="945" alt="Screenshot (1665)" src="https://github.com/user-attachments/assets/a928fa9c-5bc4-475a-9cba-cb0b045e5d3b">

**Comment by birgitta410** [comment]
@RajikaJain Ah right, that's our fault, we did some bigger changes and haven't tagged a new version yet. Can you try again by using the latest Haiven Docker image, instead ov "v0.3"?
That would mean to use ghcr.io/tw-haiven/haiven:main

Apologies for the inconvenience.

**Comment by RajikaJain** [comment]
We encountered a runtime error when attempting to load a FAISS index using faiss.read_index. The error message indicates that the index type 0x73726576 ("vers") is not recognized. This appears to be a version mismatch or file corruption issue while reading the index file.
**Command running** -  docker run         -v ./haiven-sample-knowledge-pack:/knowledge-pack         --env-file .env         -e AUTH_SWITCHED_OFF=true         -e KNOWLEDGE_PACK_PATH=/knowledge-pack         -p 8081:8080         ghcr.io/tw-haiven/haiven:main
<img width="943" alt="Screenshot (1672)" src="https://github.com/user-attachments/assets/dccaa4cb-5d65-4db8-9163-f0c137ba84ba">

**Comment by birgitta410** [comment]
@RajikaJain I have two questions to better help me understand and try to reproduce:

1. In your .env file, which model provider are you using? (Azure, Ollama, OpenAI, ...)

2. Did you change anything in the knowledge pack, or does this happen with a fresh clone?

**Comment by RajikaJain** [comment]
1. I am using Azure 
2.  It is happening with the fresh clone 
Tried to build with both the version ghcr.io/tw-haiven/haiven:main and :v0.3
From the initial investigation i think there is an error in embeddings on haiven-sample-knowledge-pack 
Path : embeddings/blips_vol_30_azure.kb/index.faiss

**Comment by birgitta410** [comment]
I cannot reproduce this on my machine unfortunately, the command seems to work fine for me, with Azure and a fresh clone. I wonder what else could be different between our machines, maybe operating system?

I just also tried to run it with the latest packaged image that contains the sample knowledge pack, that also worked:

`docker run --env-file ./app/.env -e KNOWLEDGE_PACK_PATH=knowledge-pack -e AUTH_SWITCHED_OFF=true -p 8081:8080 ghcr.io/tw-haiven/haiven-sample-knowledge-pack:main`

**Comment by RajikaJain** [comment]
Hi @birgitta410 
I was able to successfully build Haiven using the image **ghcr.io/tw-haiven/haiven-sample-knowledge-pack:main** on my Ubuntu machine. However, I want to modify the sample knowledge pack and mount it externally. I attempted to run a fresh sample knowledge pack mounted externally using the following command:


docker run \
      -v ./haiven-sample-knowledge-pack:/knowledge-pack \
    --env-file .env \
    -e AUTH_SWITCHED_OFF=true \
    -e KNOWLEDGE_PACK_PATH=/knowledge-pack \
    -p 8081:8080 \
    ghcr.io/tw-haiven/haiven:main
I am encountering an error mentioned above. Could you please try mounting the sample knowledge pack externally and test it for Azure in Linux machine if possible to reproduce the above issue.

**Comment by birgitta410** [comment]
@RajikaJain Unfortunately, I do not have a Linux machine available to test this right now.

If you just want to see the application running, you could also consider emptying the embeddings folder in the knowledge pack and remove the source of the problem that way. We put a few documents in there as examples for people, but they are not crucial to the application, and maybe are not even useful to your context (you mentioned e.g. that you suspect it might be the indexed radar volume, that is really just an example). If it is really important to you to run it with the documents we have embedded here (an indexed martinfowler.com etc), then that wouldn't solve the problem though.

**Comment by RajikaJain** [comment]
Thankyou @birgitta410 
 We appreciate your support in setting it up, and it's running smoothly with the provided image.
While exploring, we noticed a potential HTML injection issue on the Threat Modeling page. Please have a look
<img width="959" alt="Screenshot (1683)" src="https://github.com/user-attachments/assets/e5af832e-97c4-4c7c-b7ff-814b45ca7812">

[Haiven.Potential.Reflected.XSS.HTML.injection.docx](https://github.com/user-attachments/files/17148594/Haiven.Potential.Reflected.XSS.HTML.injection.docx)

**Comment by birgitta410** [comment]
@RajikaJain Oh wow, thank you so much for reporting that! We'll have a look at it. Thanks for making the effort to write it down for us.
